apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-demo-deployment.yaml
  - backend-demo-service.yaml
  - namespace-local.yaml
images:
  - name: backend-demo
    newTag: v2